BACK_BUTTON_TEXT = "🔙 Назад"
JOIN_TEAM_BUTTON_TEXT = "👥 Присоедениться к команде"
VIEW_TEAMS_BUTTON_TEXT = "👀 Посмотреть список всех команд"
MY_TEAM_BUTTON_TEXT = "🧑‍💻 Моя команда"
CANCEL_JOIN_TEAM_BUTTON_TEXT = "⛔ Нет, выбрать другую команду"
JOIN_TEAM_CONFIRMATION_BUTTON_TEXT = "👌 Да, присоедениться к команде"
CANCEL_LEAVE_TEAM_BUTTON_TEXT = "⛔ Нет, остаться в команде"
LEAVE_TEAM_CONFIRMATION_BUTTON_TEXT = "👌 Да, покинуть к команду"
LEAVE_TEAM_BUTTON_TEXT = "🏃 Покинуть команду"
DELETE_TEAM_MEMBERS_BUTTON_TEXT  = "📝 Редактировать список команды"
CANCEL_DELETE_TEAM_MEMBERS_BUTTON_TEXT  = "✋ Покинуть меню удаления"
DELETE_TEAM_MEMBER_BUTTON_TEXT = "👌 Да, удалить "
CANCEL_DELETE_TEAM_MEMBER_BUTTON_TEXT = "❌ Нет, отменить удаление"
DELETE_TEAM_MEMBER_START_BUTTON_TEXT = "✏️ Удалить: "